### ISSUE TITLE
It doesn't show up

### ISSUE THREAD

**Issue by xpde** [TristianK3604/mofh-theme#1]
Whenever I view the repository, nothing shows up? I think my computer isn't registering it in my localhost database. I spilled pickle jelly on my computer, make me a contributor.

**Comment by PlanetGamingGG** [comment]
The Repostory is still empty tho
How to create a new css?
I cant seem to find the button

**Comment by TristianK3604** [comment]
@PlanetGamingGG ill add you, just a sec @xpde there's nothing there yet

**Comment by TristianK3604** [comment]
@code just actually read your comment, what's pickle jelly?

**Comment by TristianK3604** [comment]
@xpde stupid autocorrect

**Comment by TristianK3604** [comment]
Good job, @PlanetGamingGG , you figured out how to use GitHub.

**Comment by TristianK3604** [comment]
Should I create a project board?
